# Generated by Django 4.1.2 on 2022-10-24 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0003_alter_pessoa_sexo'),
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_realizacao', models.DateField()),
                ('mandado', models.FileField(blank=True, null=True, upload_to='mandados/')),
                ('relatorio', models.FileField(blank=True, null=True, upload_to='relatório/')),
                ('dinheiro_apreendido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('obs', models.TextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco')),
                ('pessoa', models.ManyToManyField(blank=True, to='pessoas.pessoa')),
            ],
        ),
    ]
